### PR TITLE
Fixes/addresses #1481, left a TODO for the `error_method` implementation

### PR DESCRIPTION
**Pull request by dcfidalgo**
When choosing a different `method` and `err_method`, the current code fails:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-003331b1746c> in <module>()
      3 stacked_fit = SpectrumFit(obs_list=stacked_obs, model=model, method='iminuit', err_method='sherpa')
      4 stacked_fit.fit()
----> 5 stacked_fit.est_errors()
      6 
      7 

/media/david/Data/Programs/gammapy-code/gammapy/gammapy/spectrum/fit.py in est_errors(self)
    500         """Estimate parameter errors."""
    501         if self.err_method == 'sherpa':
--> 502             self._est_errors_sherpa()
    503         elif self.err_method == 'iminuit':
    504             self._est_errors_iminuit()

/media/david/Data/Programs/gammapy-code/gammapy/gammapy/spectrum/fit.py in _est_errors_sherpa(self)
    533     def _est_errors_sherpa(self):
    534         """Wrapper around Sherpa error estimator."""
--> 535         covar = self._sherpa_fit.est_errors()
    536         self.covar_axis = [par.split('.')[-1] for par in covar.parnames]
    537         self.covariance = copy.deepcopy(covar.extra_output)

AttributeError: 'SpectrumFit' object has no attribute '_sherpa_fit'
```
This PR fixes the fail described in #1481 and leaves a TODO for the proper implementation of an `error_method`.

### CODE REVIEW

**Comment by cdeil** [comment]
@joleroi - Merge?

**Comment by cdeil** [comment]
Thanks!
