### PR TITLE
Expression not assigned

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
**Description**

Fix DeepSource.io alert introduced by #3610 / 0538675:

> An expression that is not a function call is assigned to nothing. Probably something else was intended here. We recommend to review this.

### CODE REVIEW

**Review by adonath — APPROVED** [review]
Thanks!
