### ISSUE TITLE
gammapy.maps.WcsGeom.create fails to access galactic coordinate.

### ISSUE THREAD

**Issue by 9635065235** [gammapy/gammapy#2773]
`m_geom = WcsGeom.create(
    binsz=0.02, width=(1.5,1.5),skydir=(359.95,0.4),frame="galactic", proj="AIT"
) `
Which shows  the following error:
`TypeError: create() got an unexpected keyword argument 'frame'`

It only works fine for  Equatorial ("icrs") co-ordinate system not for Galactic although in the documentation there 'frame' parameter exists.

**Comment by registerrier** [comment]
Are you using v0.16? This is normally working with v0.16.

For previous versions, you should replace the `frame` keyword by `coordsys`. This change was introduced to have better consistency with `astropy.coordinates`.

**Comment by 9635065235** [comment]
I am using version0.15. 
I will upgrade my gammapy  to v0.16.
Thanks.
