### ISSUE TITLE
matplotlib minimum version is incorrect

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#1461]
In `setup.py` the required minimum for mpl is set to be 1.5, while the code uses features that was introduced into mpl 2.1. 
To filter out these cases, some older versions could be tested on travis, e.g. it can be easily controlled with the `MATPLOTLIB_VERSION` variable. 

E.g.
```

    def _get_times_and_errors(self, time_format='mjd'):
        """Extract times and corresponding errors
    
            Helper function for the plot method.
    
            Parameters
            ----------
            time_format : {'mjd', 'iso'}, optional
                Time format of the times. If 'iso', times and errors will be
                returned as `~datetime.datetime` and `~datetime.timedelta` objects
    
            Returns
            -------
            x : `~numpy.ndarray` of `float` or of `~datetime.datetime`
                Time values or `~datetime.datetime` instances if 'iso' is chosen
                as time format
            (xn, xp) : (`~numpy.ndarray` of `float` or of `~datetime.timedelta`,
                        `~numpy.ndarray` of `float` or of `~datetime.timedelta`)
                Tuple of time error values or `~datetime.timedelta` instances if
                'iso' is chosen as time format
            """
>       from matplotlib.dates import num2timedelta
E       ImportError: cannot import name 'num2timedelta'

gammapy/time/lightcurve.py:325: ImportError
```

**Comment by cdeil** [comment]
Adding this to the v0.8 milestone.

@adonath or @bsipocz Maybe for plotting it's OK to require something very recent, just to spare the  work of adding a build / test against older version and updating to work with MPL < 2.0?
Or should we just do the not very large work to support MPL 1.5, i.e. rewrite this function and add a build for MPL 1.5?
See https://pypi.org/project/matplotlib/#history for the dates

**Comment by bsipocz** [comment]
I feel it's reasonable to require a recent mpl, but I have know knowledge about gammapy's userbase.

**Comment by adonath** [comment]
@cdeil I think it's OK to require MPL >= 2.0, as most users will prefer the nicer plots by default anyway...

**Comment by cdeil** [comment]
I changes the MPL version number mentioned in setup.py in 7e46bfde56d11ed051ee68163c44236dbb9f095f . I don't think we should spend time to do more (like add more CI builds with older MPL versions).

Closing this now, but @bsipocz or @adonath - feel free to re-open if you think something else should be done.
